import { Elysia, t } from "elysia";

import "@hs/endpoints/src/query";
import "@hs/endpoints/src/server";
import { config } from "../../config";

// PUT uri: `/_matrix/federation/v1/send_join/${params.roomId}/${event.state_key}?omit_members=true`,

export const sendJoinEndpoint = new Elysia().put(
	"/send_join/:roomId/:stateKey",
	async ({ params, body }) => {
		const roomId = decodeURIComponent(params.roomId);
		const stateKey = decodeURIComponent(params.stateKey);
		const event = body as any;

		console.log("sendJoin ->", { roomId, stateKey });
		console.log("sendJoin ->", { body });

		const { eventsCollection } = await import("../../mongodb");

		// if (!(await eventsCollection.findOne({ _id: stateKey }))) {
		// 	await eventsCollection.insertOne({
		// 		_id: stateKey,
		// 		event,
		// 	});
		// }

		const events = await eventsCollection
			.find({ "event.room_id": roomId }, { sort: { "event.depth": 1 } })
			.toArray()
			.then((events) => events.map((event) => event.event));

		// console.log("lastEvent ->", lastEvent);

		// const joinEvent = events.pop();
		const result = {
			event: {
				...event,
				// TODO: Add the missing fields
				// unsigned: {
				// 	replaces_state: "$TuyDZggdD4aXn2dKI7_EuQwn92eZu13QoPtLlGO-0p8",
				// 	prev_content: {
				// 		is_direct: true,
				// 		displayname: "@a3:rc1",
				// 		avatar_url: "mxc://matrix.org/MyC00lAvatar",
				// 		membership: "invite",
				// 	},
				// 	prev_sender: "@admin:hs1",
				// },
			},
			state: events,
			auth_chain: events.filter((event) => event.depth <= 4),
			// auth_chain: [],
			members_omitted: false,
			origin: config.name,
		};

		console.log("sendJoin result ->", result);

		return result;
	},
	{
		params: t.Object(
			{
				roomId: t.String({
					// description: "The room ID that the user is being invited to.",
				}),
				stateKey: t.String({
					// description:
					// 	"The user ID for the invite event, generated by the inviting server.",
				}),
			},
			{
				examples: [
					{
						roomId: "!abc123:matrix.org",
						userId: "@admin:example.org",
					},
				],
			},
		),
	},
);
